import { LayoutDashboard,
  Layers,
  Globe,
  Building2,
  HardHat,
  FolderOpen,
  Brain,
  Activity,
  Ruler
} from 'lucide-react';

export const ENGINEERING_MODULES = [
  {
    id: "dashboard",
    title: "Dashboard",
    description: "Overview of design suite, recent activity, and command center.",
    color: "slate",
    icon: LayoutDashboard,
    status: "ready",
    route: "/",
    category: "Main",
  },
  {
    id: "pile-capacity",
    title: "Pile Capacity Calculator",
    description: "Compute shaft resistance and end bearing capacity for bored/driven concrete piles.",
    color: "blue",
    icon: Layers,
    status: "ready",
    route: "/pile-capacity",
    category: "Foundation Engineering",
  },
  {
    id: "sbc",
    title: "Safe Bearing Capacity",
    description: "IS 6403:1981 Safe Bearing Capacity Calculator",
    color: "emerald",
    icon: Globe,
    status: "ready",
    route: "/sbc",
    category: "Foundation Engineering",
  },
  {
    id: "footing-raft",
    title: "Footing & Raft Design",
    description: "Net Safe Bearing Pressure Calculator",
    color: "amber",
    icon: Building2,
    status: "ready",
    route: "/footing-raft",
    category: "Foundation Engineering",
  },
  {
    id: "under-reamed-pile",
    title: "Under-Reamed Pile Design",
    description: "Bored concrete piles with multi-bulbs in expansive clay / black cotton soils.",
    color: "indigo",
    icon: HardHat,
    status: "ready",
    route: "/under-reamed-pile",
    category: "Foundation Engineering",
  },
  {
    id: "foundation-analysis",
    title: "Foundation Analysis",
    description: "SPT, adhesion factor and IS:2911 Nq analysis",
    color: "blue",
    icon: Activity,
    status: "ready",
    route: "/foundation-analysis",
    category: "Foundation Engineering",
  },
  {
    id: "soil-classification",
    title: "Soil Classification",
    description: "USCS Soil Classification & Engineering Properties",
    color: "green",
    icon: Layers,
    status: "ready",
    route: "/soil-classification",
    category: "Geotechnical Engineering",
  },
  {
    id: "projects",
    title: "Saved Projects",
    description: "Organize client files, site data, and calculation design histories.",
    color: "teal",
    icon: FolderOpen,
    status: "ready",
    route: "/projects",
    category: "Project Management",
  },
  {
    id: "antigravity",
    title: "Antigravity",
    description: "AI engineering assistant – analysis, recommendations, and chat.",
    color: "purple",
    icon: Brain,
    status: "ready",
    route: "/antigravity",
    category: "Project Management",
  },
];
